//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int Id { get; set; }
        public Nullable<int> cart_product_id { get; set; }
        public string cart_product_name { get; set; }
        public int cart_product_price { get; set; }
        public int cart_product_quantity { get; set; }
    }
}
