//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class hutang
    {
        public int Id { get; set; }
        public int nota_id { get; set; }
        public string debtor_name { get; set; }
        public string debtor_email { get; set; }
        public string debtor_phone_number { get; set; }
        public string debtor_address { get; set; }
        public System.DateTime debtor_deadline { get; set; }
        public int debt_reminder_frequency { get; set; }
        public int debt_total { get; set; }
    
        public virtual nota nota { get; set; }
    }
}
