//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaQ.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<nota> nota { get; set; }
        public virtual DbSet<nota_detail> nota_detail { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<hutang> hutang { get; set; }
    }
}
