//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota_detail
    {
        public int Id { get; set; }
        public int nota_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string product_name { get; set; }
        public int product_price { get; set; }
        public int product_quantity { get; set; }
    
        public virtual product product { get; set; }
        public virtual nota nota { get; set; }
    }
}
