//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nota()
        {
            this.nota_detail = new HashSet<nota_detail>();
            this.hutang = new HashSet<hutang>();
        }
    
        public int Id { get; set; }
        public string buyer_name { get; set; }
        public string buyer_phone_number { get; set; }
        public System.DateTime buy_date { get; set; }
        public Nullable<int> employee_id { get; set; }
        public int total_price { get; set; }
        public int total_payment { get; set; }
        public string payment_method { get; set; }
    
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nota_detail> nota_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hutang> hutang { get; set; }
    }
}
